/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_kuwo_sing_logic_AudioLogic */

#ifndef _Included_cn_kuwo_sing_logic_AudioLogic
#define _Included_cn_kuwo_sing_logic_AudioLogic
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_cn_kuwo_sing_logic_AudioLogic_revInit
  (JNIEnv *, jobject);
  
/*
 * Class:     cn_kuwo_sing_logic_AudioLogic
 * Method:    process
 * Signature: (III[BI)V
 */
JNIEXPORT void JNICALL Java_cn_kuwo_sing_logic_AudioLogic_revProcess
(JNIEnv * env, jobject job, jint samp_freq, jint nchannels, jbyteArray samples0);

/*
 * Class:     cn_kuwo_sing_logic_AudioLogic
 * Method:    setRev
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_kuwo_sing_logic_AudioLogic_revSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_kuwo_sing_logic_AudioLogic
 * Method:    unInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_kuwo_sing_logic_AudioLogic_revRelease
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
