//
//  EAudioStreamErrorCode.h
//  KwSing
//
//  Created by 永杰 单 on 12-8-13.
//  Copyright (c) 2012年 酷我音乐. All rights reserved.
//

#ifndef KwSing_EAudioStreamErrorCode_h
#define KwSing_EAudioStreamErrorCode_h

enum AudioStreamErrorCode{
    E_AUDIO_NO_ERR,
    E_AUDIO_UNKNOW_ERR,
    E_AUDIO_FILE_READ_ERR,
    E_AUDIO_FILE_SEEK_ERR,
    E_AUDIO_STREAM_GET_PROPERTY_ERR,
    E_AUDIO_STREAM_SEEK_FAILED,
    E_AUDIO_STREAM_PHASE_BYTES_ERR,
    E_AUDIO_STREAM_OPEN_ERR,
    E_AUDIO_STREAM_CLOSE_ERR,
    E_AUDIO_DATA_NOT_EXIST,
    E_AUDIO_QUEUE_CREATE_ERR,
    E_AUDIO_QUEUE_ADD_LISTENER_ERR,
    E_AUDIO_QUEUE_BUFFER_ALLOC_ERR,
    E_AUDIO_QUEUE_ENQUEUE_ERR,
    E_AUDIO_QUEUE_START_ERR,
    E_AUDIO_QUEUE_PAUSE_ERR,
    E_AUDIO_QUEUE_BUFFER_MISMATCH,
    E_AUDIO_QUEUE_DISPOSE_ERR,
    E_AUDIO_QUEUE_STOP_ERR,
    E_AUDIO_QUEUE_FLUSH_ERR,
    E_AUDIO_QUEUE_GET_TIME_ERR,
    E_AUDIO_QUEUE_BUFFER_TOO_SMALL
};

#endif
