/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_kuwo_sing_logic_AudioLogic */

#ifndef _Included_cn_kuwo_sing_logic_AudioLogic
#define _Included_cn_kuwo_sing_logic_AudioLogic
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL
Java_cn_kuwo_base_codec_NativeAACEncoder_init( JNIEnv* env,
                                         jobject thiz,
                                         jint bitrate,
                                         jint channels,
                                         jint sampleRate,
                                         jint bitsPerSample,
                                         jstring outputFile);

JNIEXPORT void JNICALL
Java_cn_kuwo_base_codec_NativeAACEncoder_encode( JNIEnv* env,
                                           jobject thiz,
                                           jbyteArray inputArray);

JNIEXPORT void JNICALL
Java_cn_kuwo_base_codec_NativeAACEncoder_uninit( JNIEnv* env,
                                           jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
