/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_kuwo_hd_base_codec_NativeAACDecoder */

#ifndef _Included_cn_kuwo_hd_base_codec_NativeAACDecoder
#define _Included_cn_kuwo_hd_base_codec_NativeAACDecoder
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    native_get_valid_frame_position
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_native_1get_1valid_1frame_1position
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    openFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_openFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    isReadFinished
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_isReadFinished
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    getChannelNum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_getChannelNum
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    getBitrate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_getBitrate
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    getSamplerate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_getSamplerate
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    getDuration
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_getDuration
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    getCurrentPosition
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_getCurrentPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    seekTo
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_seekTo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    getSamplePerFrame
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_getSamplePerFrame
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    readSamples
 * Signature: (ILjava/nio/ShortBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_readSamples__ILjava_nio_ShortBuffer_2I
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    readSamples
 * Signature: (I[SI)I
 */
JNIEXPORT jint JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_readSamples__I_3SI
  (JNIEnv *, jobject, jint, jshortArray, jint);

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    readSamples
 * Signature: (ILjava/nio/FloatBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_readSamples__ILjava_nio_FloatBuffer_2I
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    closeFile
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_closeFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_kuwo_hd_base_codec_NativeAACDecoder
 * Method:    downsampling
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_kuwo_base_codec_NativeAACDecoder_downsampling
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
